"""Define constants."""
import logging

LOGGER = logging.getLogger("ecowitt2mqtt")

DATA_POINT_BAROMABSIN = "baromabsin"
DATA_POINT_BAROMRELIN = "baromrelin"
DATA_POINT_DAILYRAININ = "dailyrainin"
DATA_POINT_DEWPOINT = "dewpointf"
DATA_POINT_EVENTRAININ = "eventrainin"
DATA_POINT_FEELSLIKEF = "feelslikef"
DATA_POINT_HEATINDEX = "heatindex"
DATA_POINT_HOURLYRAININ = "hourlyrainin"
DATA_POINT_HUMIDITY = "humidity"
DATA_POINT_HUMIDITYIN = "humidityin"
DATA_POINT_MAXDAILYGUST = "maxdailygust"
DATA_POINT_MONTHLYRAININ = "monthlyrainin"
DATA_POINT_RAINRATEIN = "rainratein"
DATA_POINT_SOLARRADIATION = "solarradiation"
DATA_POINT_TEMPF = "tempf"
DATA_POINT_TEMPINF = "tempinf"
DATA_POINT_TOTALRAININ = "totalrainin"
DATA_POINT_UV = "uv"
DATA_POINT_WEEKLYRAININ = "weeklyrainin"
DATA_POINT_WINDCHILL = "windchill"
DATA_POINT_WINDDIR = "winddir"
DATA_POINT_WINDGUSTMPH = "windgustmph"
DATA_POINT_WINDSPEEDMPH = "windspeedmph"
DATA_POINT_YEARLYRAININ = "yearlyrainin"
