---
version: "3"

services:
  ecowitt2mqtt:
    build:
      context: .
    container_name: ecowitt2mqtt
    environment:
      ECOWITT2MQTT_MQTT_BROKER: vernemq
      ECOWITT2MQTT_MQTT_PASSWORD: password
      ECOWITT2MQTT_MQTT_TOPIC: Test
      ECOWITT2MQTT_MQTT_USERNAME: ecowitt
      ECOWITT2MQTT_VERBOSE: "true"
    ports:
      - "8080:8080/tcp"
    restart: unless-stopped

  vernemq:
    container_name: vernemq
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_USER_ECOWITT: "password"
    image: "vernemq/vernemq:latest"
    ports:
      - "1883:1883/tcp"
    restart: unless-stopped
    user: root
