"""Define tests for data processing."""
from datetime import datetime, timezone

import pytest

from ecowitt2mqtt.const import (
    CONF_ENDPOINT,
    CONF_HASS_DISCOVERY,
    CONF_HASS_DISCOVERY_PREFIX,
    CONF_HASS_ENTITY_ID_PREFIX,
    CONF_INPUT_UNIT_SYSTEM,
    CONF_MQTT_BROKER,
    CONF_MQTT_PASSWORD,
    CONF_MQTT_PORT,
    CONF_MQTT_TOPIC,
    CONF_MQTT_USERNAME,
    CONF_OUTPUT_UNIT_SYSTEM,
    CONF_PORT,
    CONF_RAW_DATA,
    CONF_VERBOSE,
    DATA_POINT_LIGHTNING,
    UNIT_SYSTEM_IMPERIAL,
    UNIT_SYSTEM_METRIC,
)
from ecowitt2mqtt.data import process_data

from tests.common import (
    TEST_ENDPOINT,
    TEST_HASS_DISCOVERY_PREFIX,
    TEST_HASS_ENTITY_ID_PREFIX,
    TEST_MQTT_BROKER,
    TEST_MQTT_PASSWORD,
    TEST_MQTT_PORT,
    TEST_MQTT_TOPIC,
    TEST_MQTT_USERNAME,
    TEST_PORT,
)


@pytest.mark.parametrize("device_payload_filename", ["payload_gw2000a_1.json"])
def test_missing_distance(device_payload, ecowitt):
    """Test that a distance key with an invalid value doesn't throw an error."""
    device_payload[DATA_POINT_LIGHTNING] = ""
    processed_data = process_data(ecowitt, device_payload)
    assert processed_data == {
        "runtime": 3179,
        "tempin": 71.2,
        "humidityin": 49,
        "baromrel": 28.476,
        "baromabs": 28.476,
        "temp": 74.5,
        "humidity": 47,
        "winddir": 100,
        "windspeed": 1.34,
        "windgust": 2.24,
        "maxdailygust": 2.24,
        "solarradiation": 0.0,
        "solarradiation_lux": 0.0,
        "solarradiation_perceived": 0.0,
        "uv": 0,
        "rrain_piezo": 0.000,
        "erain_piezo": 0.000,
        "hrain_piezo": 0.000,
        "drain_piezo": 0.000,
        "wrain_piezo": 0.000,
        "mrain_piezo": 0.000,
        "yrain_piezo": 0.000,
        "ws90cap_volt": 0.6,
        "ws90_ver": 119,
        "lightning_num": 1,
        "wh57batt": 5,
        "wh90batt": 3.16,
        "dewpoint": 53.0,
        "feelslike": 74.5,
        "heatindex": 73.9,
        "windchill": None,
    }


@pytest.mark.parametrize(
    "device_payload_filename,expected_output",
    [
        (
            "payload_gw1000bpro.json",
            {
                "runtime": 319206,
                "tempin": 79.5,
                "humidityin": 31,
                "baromrel": 24.74,
                "baromabs": 24.74,
                "temp": 89.1,
                "humidity": 14,
                "winddir": 139,
                "windspeed": 0.89,
                "windgust": 1.12,
                "maxdailygust": 8.05,
                "solarradiation": 264.61,
                "solarradiation_lux": 33494.9,
                "solarradiation_perceived": 90.0,
                "uv": 2,
                "rainrate": 0.000,
                "eventrain": 0.000,
                "hourlyrain": 0.000,
                "dailyrain": 0.000,
                "weeklyrain": 0.000,
                "monthlyrain": 2.177,
                "yearlyrain": 4.441,
                "wh65batt": 0,
                "dewpoint": 33.7,
                "feelslike": 85.1,
                "heatindex": 85.1,
                "windchill": None,
            },
        ),
        (
            "payload_gw1000pro.json",
            {
                "tempin": 76.8,
                "humidityin": 26,
                "baromrel": 24.604,
                "baromabs": 24.604,
                "temp": 56.7,
                "humidity": 27,
                "winddir": 46,
                "windspeed": 0.89,
                "windgust": 4.47,
                "maxdailygust": 15.88,
                "solarradiation": 25.56,
                "solarradiation_lux": 3235.4,
                "solarradiation_perceived": 70.0,
                "uv": 0,
                "rainrate": 0.000,
                "eventrain": 0.000,
                "hourlyrain": 0.000,
                "dailyrain": 0.000,
                "weeklyrain": 0.000,
                "monthlyrain": 0.000,
                "yearlyrain": 11.756,
                "totalrain": 11.756,
                "wh65batt": 0,
                "dewpoint": 23.1,
                "feelslike": 56.7,
                "heatindex": 53.3,
                "windchill": None,
            },
        ),
        (
            "payload_gw1100b.json",
            {
                "tempin": 76.5,
                "humidityin": 46,
                "baromrel": 29.244,
                "baromabs": 29.244,
                "temp": 91.4,
                "humidity": 48,
                "rainrate": 0.000,
                "eventrain": 0.000,
                "hourlyrain": 0.000,
                "dailyrain": 0.000,
                "weeklyrain": 0.004,
                "monthlyrain": 1.402,
                "yearlyrain": 48.504,
                "totalrain": 48.504,
                "temp1": 77.7,
                "humidity1": 51,
                "soilmoisture1": 40,
                "soilmoisture2": 56,
                "wh40batt": 1.6,
                "wh26batt": 0,
                "batt1": 0,
                "soilbatt1": 1.5,
                "soilbatt2": 1.8,
                "dewpoint": 68.9,
                "heatindex": 96.3,
            },
        ),
        (
            "payload_gw2000a_1.json",
            {
                "runtime": 3179,
                "tempin": 71.2,
                "humidityin": 49,
                "baromrel": 28.476,
                "baromabs": 28.476,
                "temp": 74.5,
                "humidity": 47,
                "winddir": 100,
                "windspeed": 1.34,
                "windgust": 2.24,
                "maxdailygust": 2.24,
                "solarradiation": 0.0,
                "solarradiation_lux": 0.0,
                "solarradiation_perceived": 0.0,
                "uv": 0,
                "rrain_piezo": 0.000,
                "erain_piezo": 0.000,
                "hrain_piezo": 0.000,
                "drain_piezo": 0.000,
                "wrain_piezo": 0.000,
                "mrain_piezo": 0.000,
                "yrain_piezo": 0.000,
                "ws90cap_volt": 0.6,
                "ws90_ver": 119,
                "lightning_num": 1,
                "lightning": 16.8,
                "wh57batt": 5,
                "wh90batt": 3.16,
                "dewpoint": 53.0,
                "feelslike": 74.5,
                "heatindex": 73.9,
                "windchill": None,
            },
        ),
        (
            "payload_gw2000a_2.json",
            {
                "runtime": 436796,
                "tempin": 72.9,
                "humidityin": 56,
                "baromrel": 29.870,
                "baromabs": 29.509,
                "temp": 59.7,
                "humidity": 65,
                "winddir": 327,
                "windspeed": 2.24,
                "windgust": 3.80,
                "maxdailygust": 17.45,
                "solarradiation": 0.00,
                "solarradiation_lux": 0.0,
                "solarradiation_perceived": 0.0,
                "uv": 0,
                "rainrate": 0.000,
                "eventrain": 0.000,
                "hourlyrain": 0.000,
                "dailyrain": 0.000,
                "weeklyrain": 0.000,
                "monthlyrain": 0.736,
                "yearlyrain": 3.909,
                "rrain_piezo": 0.000,
                "erain_piezo": 0.063,
                "hrain_piezo": 0.000,
                "drain_piezo": 0.075,
                "wrain_piezo": 0.075,
                "mrain_piezo": 0.941,
                "yrain_piezo": 4.114,
                "ws90cap_volt": 5.2,
                "ws90_ver": 115,
                "temp1": 71.2,
                "humidity1": 61,
                "temp2": 71.2,
                "humidity2": 58,
                "temp3": 70.5,
                "humidity3": 61,
                "temp4": 73.0,
                "humidity4": 58,
                "temp5": 70.7,
                "humidity5": 69,
                "temp6": 72.7,
                "humidity6": 58,
                "temp7": 67.1,
                "humidity7": 54,
                "temp8": 68.0,
                "humidity8": 56,
                "soilmoisture1": 53,
                "soilmoisture2": 57,
                "soilmoisture3": 59,
                "soilmoisture4": 49,
                "soilmoisture5": 52,
                "pm25_ch1": 21.0,
                "pm25_avg_24h_ch1": 16.3,
                "tf_co2": 62.2,
                "humi_co2": 61,
                "pm25_co2": 4.9,
                "pm25_24h_co2": 7.5,
                "pm10_co2": 6.1,
                "pm10_24h_co2": 7.8,
                "co2": 455,
                "co2_24h": 473,
                "lightning_num": 13,
                "lightning": 0.6,
                "lightning_time": datetime(
                    2022, 4, 20, 17, 17, 17, tzinfo=timezone.utc
                ),
                "wh80batt": 3.28,
                "batt1": 0,
                "batt2": 0,
                "batt3": 0,
                "batt4": 0,
                "batt5": 0,
                "batt6": 0,
                "batt7": 0,
                "batt8": 0,
                "soilbatt1": 1.4,
                "soilbatt2": 1.3,
                "soilbatt3": 1.3,
                "soilbatt4": 1.3,
                "soilbatt5": 1.3,
                "pm25batt1": 3,
                "wh57batt": 3,
                "co2_batt": 6,
                "wh90batt": 3.22,
                "dewpoint": 47.9,
                "feelslike": 59.7,
                "heatindex": 58.4,
                "windchill": None,
            },
        ),
        (
            "payload_pthp2550pro.json",
            {
                "tempin": 64.4,
                "humidityin": 72,
                "baromrel": 28.196,
                "baromabs": 28.196,
                "temp": 50.9,
                "humidity": 96,
                "winddir": 289,
                "winddir_avg10m": 282,
                "windspeed": 2.7,
                "windspdmph_avg10m": 2.5,
                "windgust": 6.9,
                "maxdailygust": 20.6,
                "rainrate": 0.000,
                "eventrain": 0.134,
                "hourlyrain": 0.012,
                "dailyrain": 0.134,
                "weeklyrain": 0.134,
                "monthlyrain": 1.110,
                "yearlyrain": 11.610,
                "solarradiation": 174.81,
                "solarradiation_lux": 22127.8,
                "solarradiation_perceived": 87.0,
                "uv": 1,
                "temp1": 66.4,
                "humidity1": 69,
                "soilmoisture1": 22,
                "pm25_ch1": 7.0,
                "pm25_avg_24h_ch1": 14.3,
                "wh65batt": 0,
                "wh25batt": 0,
                "batt1": 0,
                "soilbatt1": 1.5,
                "pm25batt1": 5,
                "dewpoint": 49.8,
                "feelslike": 50.9,
                "heatindex": 50.2,
                "windchill": None,
            },
        ),
        (
            "payload_ws2900.json",
            {
                "tempin": 72.9,
                "humidityin": 62,
                "baromrel": 29.829,
                "baromabs": 28.122,
                "temp": 57.2,
                "humidity": 87,
                "winddir": 271,
                "windspeed": 6.9,
                "windgust": 9.2,
                "maxdailygust": 9.2,
                "rainrate": 0.000,
                "eventrain": 1.331,
                "hourlyrain": 0.000,
                "dailyrain": 0.000,
                "weeklyrain": 1.331,
                "monthlyrain": 4.929,
                "totalrain": 14.890,
                "solarradiation": 0.00,
                "solarradiation_lux": 0.0,
                "solarradiation_perceived": 0.0,
                "uv": 0,
                "wh65batt": 0,
                "dewpoint": 53.4,
                "feelslike": 57.2,
                "heatindex": 56.7,
                "windchill": None,
            },
        ),
    ],
)
def test_process(device_payload, device_payload_filename, ecowitt, expected_output):
    """Test processing a raw data payload."""
    processed_data = process_data(ecowitt, device_payload)
    assert processed_data == expected_output


@pytest.mark.parametrize(
    "config",
    [
        {
            CONF_ENDPOINT: TEST_ENDPOINT,
            CONF_HASS_DISCOVERY: False,
            CONF_HASS_DISCOVERY_PREFIX: TEST_HASS_DISCOVERY_PREFIX,
            CONF_HASS_ENTITY_ID_PREFIX: TEST_HASS_ENTITY_ID_PREFIX,
            CONF_INPUT_UNIT_SYSTEM: UNIT_SYSTEM_IMPERIAL,
            CONF_MQTT_BROKER: TEST_MQTT_BROKER,
            CONF_MQTT_PASSWORD: TEST_MQTT_PASSWORD,
            CONF_MQTT_PORT: TEST_MQTT_PORT,
            CONF_MQTT_TOPIC: TEST_MQTT_TOPIC,
            CONF_MQTT_USERNAME: TEST_MQTT_USERNAME,
            CONF_OUTPUT_UNIT_SYSTEM: UNIT_SYSTEM_METRIC,
            CONF_PORT: TEST_PORT,
            CONF_RAW_DATA: False,
            CONF_VERBOSE: False,
        }
    ],
)
def test_unit_system(device_payload, device_payload_filename, ecowitt):
    """Test converting imperial data to metric."""
    processed_data = process_data(ecowitt, device_payload)
    assert processed_data == {
        "runtime": 319206,
        "tempin": 26.4,
        "humidityin": 31,
        "baromrel": 837.793,
        "baromabs": 837.793,
        "temp": 31.7,
        "humidity": 14,
        "winddir": 139,
        "windspeed": 1.4,
        "windgust": 1.8,
        "maxdailygust": 8.05,
        "solarradiation": 264.61,
        "uv": 2,
        "rainrate": 0.0,
        "eventrain": 0.0,
        "hourlyrain": 0.0,
        "dailyrain": 0.0,
        "weeklyrain": 0.0,
        "monthlyrain": 55.3,
        "yearlyrain": 112.8,
        "wh65batt": 0,
        "dewpoint": 0.9,
        "feelslike": 29.5,
        "heatindex": 29.5,
        "solarradiation_lux": 33494.9,
        "solarradiation_perceived": 90.0,
        "windchill": None,
    }
