{{ if .Values.mqtt.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  username: {{ .Values.mqtt.auth.username | b64enc }}
  password: {{ .Values.mqtt.auth.password | b64enc }}
{{ end }}
