---
name: Release Drafter

"on":
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  update_release_draft:
    name: ✏️ Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run Release Drafter
        uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
