---
name: Stale

"on":
  schedule:
    - cron: "0 8 * * *"

  workflow_dispatch:

jobs:
  stale:
    name: 🧹 Clean up stale issues and PRs
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Run stale
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          remove-stale-when-updated: true
          stale-issue-label: "stale"
          exempt-issue-labels: "no-stale,help-wanted"
          stale-issue-message: >
            There hasn't been any activity on this issue recently, so it
            has been marked as stale.

            Please make sure to update to the latest version and
            check if that solves the issue. Let us know if that works for you
            by leaving a comment.

            This issue will be closed if no further activity occurs. Thanks!
          stale-pr-label: "stale"
          exempt-pr-labels: "no-stale"
          stale-pr-message: >
            There hasn't been any activity on this pull request recently, so
            it has automatically been marked as stale and will be closed if
            no further action occurs within 7 days. Thank you for your
            contributions.
